FROM postgres:latest

ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydb

EXPOSE 5432

# docker exec -it container_id psql -h localhost -U myuser mydb

# =========================
# DATABASE / CONNECTION INFO
# =========================

# List all databases
# \l

# =========================
# TABLE METADATA
# =========================

# List all tables
# \dt

# List tables with more details
# \dt+

# Describe a table
# \d table_name

# Describe a table with extra metadata
# \d+ table_name

# List indexes
# \di

# List views
# \dv

# List sequences
# \ds