services:
  db:
    image: postgres:latest
    container_name: myapp-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./app-api
      dockerfile: Dockerfile
    container_name: myapp-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
      # ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=mydb;Username=myuser;Password=mypassword"
    ports:
      - "8080:8080"
    depends_on:
      - db

  angular:
    build:
      context: ./app-front
      dockerfile: Dockerfile
    container_name: myapp-angular
    ports:
      - "4200:80"

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  ollama-init:
    image: ollama/ollama
    depends_on:
      - ollama
    entrypoint: >
      sh -c "
      sleep 5 &&
      ollama pull llama3.2:1b
      "
    environment:
      - OLLAMA_HOST=http://ollama:11434

  text-server:
    build:
      context: ./app-text-server
      dockerfile: Dockerfile
    container_name: myapp-text-server
    ports:
      - "8000:8000"
    depends_on:
      - api


volumes:
  ollama:
#   postgres_data: