services:
  db:
    image: pgvector/pgvector:pg16
    container_name: myapp-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./app-api
      dockerfile: Dockerfile
    container_name: myapp-api
    env_file:
      - ./app-api/.env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "8080:8080"
    depends_on:
      - db

  angular:
    build:
      context: ./app-front
      dockerfile: Dockerfile
    container_name: myapp-angular
    ports:
      - "4200:80"
  text-server:
    build:
      context: ./app-text-server
      dockerfile: Dockerfile
    container_name: myapp-text-server
    ports:
      - "8000:8000"
    depends_on:
      - api


volumes:
  postgres_data: