apiVersion: apps/v1
kind: Deployment

metadata:
  name: workspaceai-text-extractor
  namespace: workspaceai-prod

spec:
  replicas: 1

  selector:
    matchLabels:
      app: workspaceai-text-extractor

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: workspaceai-text-extractor

    spec:
      containers:
        - name: workspaceai-text-extractor
          image: carlosblanco1/workspaceai-text-server:latest

          ports:
            - containerPort: 8000

          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3

          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20